### ISSUE TITLE
Remove scheduling of database backups from documentation

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq.org#1102]
https://www.manageiq.org/docs/reference/latest/general_configuration/#scheduling-smartstate-analyses-and-backups

I believe it was removed in: https://github.com/ManageIQ/manageiq/pull/21415

I don't know if that section of the documentation needs new screenshots or updated guidance but it looks old to me.

**Comment by Fryguy** [comment]
The entire section https://www.manageiq.org/docs/reference/latest/general_configuration/#scheduling-a-database-backup should be removed.  Otherwise there are a handful of screenshots in unrelated sections that show Database Backup in the dropdown that probably should be retaken

**Comment by dehawkins512** [comment]
@miq-bot assign @dehawkins512
