### ISSUE TITLE
Enhance Mobile rendering

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#112]
Since I had to juggle a lot of things to prepare for launch, I didn't get the oppertunity to optimize everything on a mobile device.

I did, when I could, make sure most stuff would work... but some things like the footer and partner graphics could use some improvement.

**Comment by JPrause** [comment]
With the upcoming redesign of the website, this request seems not be relevant at this time,..can you close this issue @garrett

**Comment by Fryguy** [comment]
Closing since the new website is now live.  If you believe this to be in error, please reopen this issue.
