### ISSUE TITLE
Dashboard customization

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#12]
I was told that having information on how to customized the dashboard.

Does documentation exist for this or does it need to be written? Is it critical for the launch?

**Comment by JPrause** [comment]
With the upcoming redesign of the website, this request seems not be relevant at this time,..can you close this issue @garrett

**Comment by Fryguy** [comment]
Closing since the new website is now live.  If you believe this to be in error, please reopen this issue.
