### ISSUE TITLE
Not clear instruction regarding kickstart file

### ISSUE THREAD

**Issue by abonas** [ManageIQ/manageiq.org#125]
The install from source page
(http://manageiq.org/community/install-from-source/)
Has this sentence:  "A lot of this has been automated in the ManageIQ kickstart file".
What does "a lot" mean?
It's very vague - it's not clear how many and which instructions are automated, and which are not.

**Comment by JPrause** [comment]
With this issue being over two years old,...can you close this issue @abonas
