### ISSUE TITLE
Procedure for updating website's appliance images

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq.org#129]
Automation tasks:
- [x] Script to upload images
- [x] Update website download links to resolve to newly uploaded image files
- [x] Further automate the existing scripts to automatically upload new nightly builds to the CDN and update website links
- [x] Make uploads of adhoc "release" branch builds a single "build + upload" task

**Comment by JPrause** [comment]
It appears this issue is no longer relevant,..can you close this issue @jrafanie
