### ISSUE TITLE
Create page about creating pages

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#135]
It's a bit meta, but there needs to be a page written about creating pages.

Sure, it's as simple as creating a file on github, but we need to clarify that, and have best practices a bit formalized.

(I will work on this with @mfeifer.)

**Comment by JPrause** [comment]
After two years of no status, this request seems not be relevant at this time,..can you close this issue @garrett

**Comment by Fryguy** [comment]
Closing since the new website is now live.  If you believe this to be in error, please reopen this issue.
