### ISSUE TITLE
Best practice: Migrating content from “Talk” to the website

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#136]
When something is discussed and a solution is found, it's a good idea to capture this officially.

The flow should be like this:

1. Discussion!
2. Someone thinks: _“Hey, this is useful!”_
3. _? ? ?_
4. _A new website page appears!_

Step 3 is what this future document is about. How does this happen? What are the best practices?

My suggestion is the following:

1. Create a new page, in Markdown, with a cleaned version of the discussion (either lifting the text directly or providing a friendly summary).
2. Send a pull request to the `manageiq.org` repo.
3. Discuss the changes there (or simply accept it if it's really quite good).
4. Merge in the pull request.
5. Link the resulting page from the original thread. (This link should probably be mentioned in the topmost comment with an editor's note, to prevent searchers, either from the forum directly or from a search engine like Google or DuckDuckGo or \*cough\* Bing, from having to read through the entire discussion.)
6. Success!

(Note: This is basically the workflow for #135, with some sprinkles on top, like having the beginner content ready and having a link back.)

(Note 2: It could be possible to create an issue to create a page with the content in-line. Then someone with access can figure out where the content belongs and polish it up. The web page about creating the page should mention this as a secondary flow.)

**Comment by JPrause** [comment]
I believe this issue is no longer relevant,..can you close this issue @garrett

**Comment by Fryguy** [comment]
Closing since the new website is now live.  If you believe this to be in error, please reopen this issue.
