### ISSUE TITLE
Add RSS feed of cloudformsnow.com to blog

### ISSUE THREAD

**Issue by johnmark** [ManageIQ/manageiq.org#184]
We need a way to add the content from John Hardy's blog into ours - it has a lot of great technical information. 

RSS feed: http://cloudformsnow.com/feed/ 

Is there a way to do this with Middleman? 

cc/ @garrett @mfeifer @jonnyfiveiq

**Comment by garrett** [comment]
What are some Atom or RSS feeds that could be integrated into the planet aggregator?

1. CloudFormsNow: http://cloudformsnow.com/feed/
...and what are some others?

**Comment by garrett** [comment]
Ping? I still need someone (@johnmark & others) to answer the questions I pose in this issue. Thanks!

**Comment by dneary** [comment]
I would be happy to answer, but John Mark needs to sign off. He was away
much of last week, and is travelling in Australia this week.

With his and John Mark's approval, I would add Bryan Che's blog
tentenet.net - aside from that one, I can't think of others that would
be appropriate. JM may know of a BAH blog that would fit the bill.

Thanks,
Dave.



On 01/13/2015 11:17 AM, Garrett LeSage wrote:
> Ping? I still need someone (@johnmark <https://github.com/johnmark> &
> others) to answer the questions I pose in this issue. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ManageIQ/manageiq.org/issues/184#issuecomment-69770644>.
> 

-- 
Dave Neary - NFV/SDN Community Strategy
Open Source and Standards, Red Hat - http://community.redhat.com
Ph: +1-978-399-2182 / Cell: +1-978-799-3338

**Comment by garrett** [comment]
It's kind of weird to have a planet with just two blog feeds. Do any of the developers of ManageIQ have blogs we can pull in?

**Comment by mfeifer** [comment]
Let me ask the crew.  Will get back to you today....

**Comment by garrett** [comment]
We have http://planet.manageiq.org/ for this and other feeds now, so I'm closing this issue.
