### ISSUE TITLE
Text with how to report a bug

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#19]
Right now, we have a link to https://bugzilla.redhat.com/enter_bug.cgi?product=ManageIQ — but it needs to be much friendlier than that. This means, we need a little bit of text with how to properly submit a bug.

Also, I think we're using GitHub for issues now... correct?

**Comment by JPrause** [comment]
With the upcoming redesign of the website, this request seems not be relevant at this time,..can you close this issue @garrett
