### ISSUE TITLE
Depot: Handle GitHub API calls for user info more gracefully

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#191]
Right now, the GitHub API is has one request per GitHub user. This is a problem, as GitHub only allows for 60 requests per hour. I've fixed it with a graceful fallback — but that's not really good enough.

Note: I do cache the info per session. Also, it should be using open-uri-cached... but since I hit the 60 API requests limit while developing today, I am assuming that some caching somewhere doesn't work properly. (I did restart the session several times while debugging stuff. I believe it is related to open-uri-cached.)

There's no way to pull information about multiple GitHub users unless you query for the _entire_ site. That's obviously a bad idea. However, the API does expose ways to query for all users for a particular group or repo.

So my idea is this:

1. Pull all user info for the ManageIQ team.
2. Pull all user info for the extensions repo.
3. Pool the pulls together.

That's only two API calls. It would _probably_ contain all the people we most likely care about. However, I can see there would be corner cases not covered. In the event someone is not on the ManageIQ team or has committed to the extensions repo, we'd look up their data on a one-off basis.

In all likelihood, we wouldn't hit the limit using this method. It should scale much better than the current one.

**Comment by Fryguy** [comment]
You can just use a token...that's what we use for the bot and we have 5000 requests an hour.

**Comment by garrett** [comment]
Yeah, except that the source code is published on GitHub.

I guess we could use this method as a fallback and then use an environmental variable for a token.

**Comment by johnmark** [comment]
What is the status of this?

**Comment by Fryguy** [comment]
@garrett For the bot, we use the [rails_config gem](https://github.com/railsconfig/rails_config), and then in deployment we just deploy, with Puppet, a settings.local.yml with the expected values, next to the default [settings.yml](https://github.com/ManageIQ/miq_bot/blob/master/config/settings.yml).  I think either that or an ENV var(s) would work fine.

**Comment by garrett** [comment]
It still isn't a problem, as building the depot will never hit the API limit under normal use. 

It was only a temporary issue when doing development on the depot. (I only hit this once, and when I was heavily working on the depot originally. Waiting an hour worked for me, and I didn't hit it afterward.)

I really think we should not spend the time on fixing this when other people are making a new version of depot with completely new code anyway, especially since this issue will _never_ be hit in production.
