### ISSUE TITLE
Fix build without nodejs installed

### ISSUE THREAD

**Issue by mscherer** [ManageIQ/manageiq.org#193]
We found that the build is broken without nodejs: 

    [middleman_builder@webbuilder root]$ cat ~/error_manageiq
    /srv/builder/.gem/ruby/gems/execjs-2.2.0/lib/execjs/runtimes.rb:51:in `autodetect': Could not find a     JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
            from /srv/builder/.gem/ruby/gems/execjs-2.2.0/lib/execjs.rb:5:in `<module:ExecJS>'
            from /srv/builder/.gem/ruby/gems/execjs-2.2.0/lib/execjs.rb:4:in `<top (required)>'
            from /srv/builder/.gem/ruby/gems/coffee-script-2.2.0/lib/coffee_script.rb:1:in `require'
            from /srv/builder/.gem/ruby/gems/coffee-script-2.2.0/lib/coffee_script.rb:1:in `<top (required)>'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/lib/middleman-core/renderers/coffee_script.rb:2:in `require'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/lib/middleman-core/renderers/coffee_script.rb:2:in `<top (required)>'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/lib/middleman-core/core_extensions/rendering.rb:34:in `require'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/lib/middleman-core/core_extensions/rendering.rb:34:in `registered'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/lib/middleman-core/core_extensions/extensions.rb:78:in `register'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/lib/middleman-core/application.rb:150:in `<class:Application>'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/lib/middleman-core/application.rb:28:in `<module:Middleman>'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/lib/middleman-core/application.rb:27:in `<top (required)>'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/lib/middleman-core.rb:15:in `require'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/lib/middleman-core.rb:15:in `<top (required)>'
            from /srv/builder/.gem/ruby/gems/middleman-3.3.3/lib/middleman.rb:1:in `require'
            from /srv/builder/.gem/ruby/gems/middleman-3.3.3/lib/middleman.rb:1:in `<top (required)>'
            from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require'
            from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
            from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
            from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `block in require'
            from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
            from /usr/share/gems/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
            from /usr/share/gems/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/lib/middleman-core/load_paths.rb:37:in `setup_load_paths'
            from /srv/builder/.gem/ruby/gems/middleman-core-3.3.3/bin/middleman:10:in `<top (required)>'
            from /srv/builder/bin/middleman:23:in `load'
            from /srv/builder/bin/middleman:23:in `<main>'

I suspect the removal of less triggered the issue, by removing therubyracer or something else. Could it be added, as I am not keen on forcing the installation of nodejs on builder (because this also mean the build is broken on others people system ) ?

**Comment by garrett** [comment]
Ah ok. Odd. I can re-add it. I guess the CoffeeScript deps aren't pulling it in then. It works fine here (probably because it might be pulling in my system-wide Node.JS), but I'll re-add it for others.
