### ISSUE TITLE
content for "Market"

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#20]
I need examples of extensions/plugins/marketlets/scripts/whatever-they're-called, so I could possibly help to build out the market area.

**Comment by JPrause** [comment]
With the upcoming redesign of the website, this request seems not be relevant at this time,..can you close this issue @garrett

**Comment by Fryguy** [comment]
Closing since the new website is now live.  If you believe this to be in error, please reopen this issue.
