### ISSUE TITLE
talk.manageiq.org reply by email does not seem to work

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq.org#200]
I've tried twice now, and the reply by email never gets posted to the topic.

**Comment by mscherer** [comment]
Firewall was in the way, it should be fixed now, can you confirm if that's ok ?
( I will watch the log to see when discourse fetch the messages )

**Comment by mscherer** [comment]
I also enabled ssl ( now this is supported ), and I am watching if this is working ( there is CA issue it seems )

**Comment by mscherer** [comment]
Ok so I deployed a proper CA, still watching of something if it work ( for some reason, dvoecot do not log any attempt to connect )

**Comment by Fryguy** [comment]
I'll see if I can reply to an email shortly.

**Comment by mscherer** [comment]
I did see the system downloading the email. I kinda got confused by the fact we need to enable ssl and change the port to make it work.

**Comment by Fryguy** [comment]
Just sent an email reply to http://talk.manageiq.org/t/what-is-the-correct-dev-setup-documentation-guide/570/4 with the content "test email"...nothing yet

**Comment by mscherer** [comment]
We did receive the email, and it was downloaded from discourse according to the logs. I am not sure I can do more from here, as the access i have on discourse are not sufficient, someone from the hoster should take a look.

**Comment by JPrause** [comment]
Seems this issue is has been resolved,..can you please close this issue @Fryguy
