### ISSUE TITLE
Redundant instruction to create miqbuilder user in "build from source" guide

### ISSUE THREAD

**Issue by abonas** [ManageIQ/manageiq.org#202]
There's no need to create and use miqbuilder, it should be removed from instructions.

Based on this conversation:
http://talk.manageiq.org/t/why-the-miqbuilder-user-is-needed-when-running-manageiq-from-source/572

**Comment by johnmark** [comment]
Thanks for the feedback. Will update the "build from source" instructions.

**Comment by JPrause** [comment]
With updated instructions found here: http://manageiq.org/documentation/development/developer_setup/ can you please close this issue @abonas
