### ISSUE TITLE
"Download and install ManageIQ" and "Download and install ManageIQ-devel" pages both link to the sprints changelog

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq.org#203]
When I go here:
http://manageiq.org/download/
And:
http://manageiq.org/download/devel/

They both link to the changelog here:
http://manageiq.org/community/changelog/

Problem:
* We don't have a "anand" changelog so it's confusing to see sprint changelogs that are NOT included in the "anand" download
* Should we remove the changelog link on the main download page?

**Comment by jrafanie** [comment]
cc @mfeifer Thoughts?

**Comment by mfeifer** [comment]
@jrafanie The text on the download pages says "See what's changed since the last release by reviewing".  Is that not clear enough?

**Comment by jrafanie** [comment]
I don't know, it's confusing to me.  I'm not sure why we link to the "devel" changelog and the "devel" download page (which also links to the "devel" changelog).

I'd prefer the download page has links to the release appliances and a link to the "devel" download page for "fixes/enhancements since the last release(unstable)" and keep the devel page the same with the link to the changelog and devel appliances.  When we release Botvinnik(sp?), it would be nice to have a separate changelog since Anand on the main download page, but as of now, it's pretty confusing.

Maybe it's just me?  Feel free to close if you think it's clear.

**Comment by johnmark** [comment]
Are there separately maintained changelogs?

**Comment by Fryguy** [comment]
@johnmark Since each one is it's own branch, yes.

**Comment by JPrause** [comment]
Seems this issue is no longer relevant as described,...can you please close @jrafanie
