### ISSUE TITLE
Botvinnik release candidate download

### ISSUE THREAD

**Issue by johnmark** [ManageIQ/manageiq.org#204]
We need to change teh language on the /download/devel pages to reflect the fact that this is an RC, not a scary nightly. Here's what I propose:

At the bottom of the /download page, replace the following:

"Like living on the edge?
Download the nightly build for testing only..."

with this language:

"Want to test the Botvinnik release candidate?
Download from here and [report any issues](https://github.com/ManageIQ/manageiq/issues)

On /download/devel page, replace the following text:

"Warning: These are instructions for the nightly build. Things may be unstable, and may break. If you're looking for adventure, please proceed. Otherwise, view instructions for the current release instead."

With this:

"Download and test the Botvinnik release candidate using the instructions below. If things break, [report an issue](https://github.com/ManageIQ/manageiq/issues) or ask questions on [talk.manageiq.org](http://talk.manageiq.org). If you meant to download the current release, Anand, instead, go back to the [main download page](/download)

**Comment by Fryguy** [comment]
So are you suggesting dropping the nightly?  I don't really like that idea.  Why can't we just have all 3?

**Comment by johnmark** [comment]
only temporarily - until the RC is done.

**Comment by johnmark** [comment]
and we won't have nightlies that aren't RCs until after the Botvinnik release.

**Comment by garrett** [comment]
Is the filename still `-devel`?

**Comment by johnmark** [comment]
no. It's manageiq-ovirt-botvinnik-1-rc1.ova

**Comment by garrett** [comment]
What does the `-1-` mean?

**Comment by johnmark** [comment]
no idea :) Adding @JPrause and @mscherer

**Comment by johnmark** [comment]
Also, the build is not yet at http://releases.manageiq.org/ - @JPrause - can you handle?

**Comment by JPrause** [comment]
Yes,..just was speaking with @jrafanie about the upload process.

**Comment by johnmark** [comment]
awesome - thank you!

**Comment by JPrause** [comment]
@garrett The files names are actually:
manageiq-openstack-botvinnik-rc1.qc2
manageiq-ovirt-botvinnik-rc1.ova
manageiq-vsphere-botvinnik-rc1.ova

**Comment by garrett** [comment]
Hopefully the patch in pull request #205 does what you want. :wink:

If you want me to work further on the patch, please let me know and I'll try to adjust it to how you want tomorrow. (It's already evening in Europe.)

**Comment by mscherer** [comment]
So the iso have been uploaded, and can be seen on http://releases.manageiq.org

I will download and do some sha1/md5sum verification

**Comment by mscherer** [comment]
Mhh, just realized that I didn't upload the file with the correct name, redoing it .

**Comment by johnmark** [comment]
@mscherer - let's follow the nomenclature from @JPrause above

**Comment by JPrause** [comment]
@johnmark - hmmm,...well it appears that the names are not what I had defined above. It appears the script modified it during upload. So the file name are:
manageiq-openstack-botvinnik-1-rc1-201503311836-7d08701ec1.qc2
manageiq-ovirt-botvinnik-1-rc1-201503311836-7d08701ec1.ova
manageiq-vsphere-botvinnik-1-rc1-201503311836-7d08701ec1.ova

I can try the upload again, if needed.

**Comment by johnmark** [comment]
Was afraid of that - @mscherer - is there a way to change the file name once uploaded?

**Comment by johnmark** [comment]
oh never mind - looks like @mscherer has it working - http://releases.manageiq.org/

So don't do anything for now :)

**Comment by mscherer** [comment]
So the 3 should have been uploaded in 5 minutes. I removed the other, but it take time to be removed from the CDN, so just ignore them.

**Comment by johnmark** [comment]
Merged - thanks everyone for the team effort!

**Comment by Fryguy** [comment]
> What does the -1- mean?

The -1- means version 1.  If we ever have to release a second botvinnik, it would be a 2.  So botvinnik-1-rc1 means the first release candidate of Botvinnik version 1.  The final release will be botvinnik-1.  A follow up release might have a botvinnik-2-rc1, and then the final release of *that* would be botvinnik-2.

**Comment by johnmark** [comment]
Thanks for the clarification.
