### ISSUE TITLE
Newsletter signup

### ISSUE THREAD

**Issue by johnmark** [ManageIQ/manageiq.org#206]
We need to bring back the newsletter signup form - we have a few hundred people signed up to it, but we need to make the form visible again.

Is there a way to add it to the home page? Or perhaps on /community

**Comment by garrett** [comment]
The code still resides in the [`simple` branch](https://github.com/ManageIQ/manageiq.org/tree/simple) @ 
https://github.com/ManageIQ/manageiq.org/blob/simple/source/index.html.haml#L48-L52:

```yaml
- form_url = "http://lists.manageiq.org/mailman/subscribe/newsletter"

= form_tag form_url, class: "form-email form-inline", method: "post", role: "form" do
  = text_field_tag :email, class: "email-address form-control", placeholder: "you@domain.com"
  = submit_tag "Subscribe!", class: "btn btn-success"
```

It should be fine to copy/paste it where it is needed. It _might_ need some SASS ported over too (`.form-email` for example), but I don't think it does.
