### ISSUE TITLE
Homebrew installation instructions are incorrect in Readme

### ISSUE THREAD

**Issue by tjferguson** [ManageIQ/manageiq.org#207]
States:
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"

Should be:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Comment by Fryguy** [comment]
@johnmark Can we please remove the website based instructions, which are old and not maintained and instead point the the documentation on the guides?
