### ISSUE TITLE
Meet the team

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#21]
If we're going to do this by launch, we need proper content for this.

That means a:

* name
* photo
* summary
* title for the person in relation to the ManageIQ project
* contact links (twitter, URL, etc.)

This is needed for every person involved.

(Note: This should probably be a programmatically generated page, based on content in a YML file in data and images under source/images/team/*png)

**Comment by JPrause** [comment]
With the upcoming redesign of the website, this request seems not be relevant at this time,..can you close this issue @garrett
