### ISSUE TITLE
Manageiq config.rb update git submodule in a incompatible way with the build script

### ISSUE THREAD

**Issue by mscherer** [ManageIQ/manageiq.org#234]
I just found out that config.rb in the repo is doing git submodule foreach "git pull -qf origin master".

However, the build script is also doing a git submodule update, and both of them are updating, then downgrading the code. And I am not sure which one to fix and how. 

@garrett , you may have a idea ? In the mean time, this make the build running in a loop, so I will disable to avoid being blkaclisted by github.

**Comment by matthewd** [comment]
The only `git submodule update` I can see is in `setup.sh`, which doesn't sound like it expects to be part of the regular build script. :confused:

**Comment by mscherer** [comment]
I can see it here too:

https://github.com/ManageIQ/manageiq.org/blob/master/config.rb#L274

**Comment by matthewd** [comment]
That's the pull... I'm trying to work out what's conflicting with that one, though.

**Comment by mscherer** [comment]
The builder, installed with this ansible role:
https://github.com/OSAS/ansible-role-middleman_builder

Basically this script:
https://github.com/OSAS/ansible-role-middleman_builder/blob/master/files/build_deploy.sh

**Comment by matthewd** [comment]
Ah, right. Looks like we really don't want https://github.com/OSAS/ansible-role-middleman_builder/blob/master/files/build_deploy.sh#L27 to happen, as our middleman script is set up to do the more aggressive pull instead.

**Comment by mscherer** [comment]
Yeah, but the script is shared for others projects, and if I remove it here, I might break on other middleman stuff around. I guess I could make it conditional, but adding option to a bash script make me sad.

**Comment by mscherer** [comment]
IE, we use that for community.redhat.com, for the planet of manageiq, for project-atomic, etc. But a rewrite in something else than bash wouldn't hurt too.

**Comment by matthewd** [comment]
`/usr/local/bin/git` that ignores `submodule update` but passes everything else along? :trollface:

Do we need a fork of that repo? :confused:

**Comment by mscherer** [comment]
Nope I just need to fix my builder script, or people need to use submodule properly. The root cause is that people forget the submodules, so we have to work around that ( ie, the part in config.rb ), but when people use submodule properly, updating to the latest submodule HEAD is the wrong thing to do. We cannot have a solution for everything so we have to add a option.

**Comment by matthewd** [comment]
Yeah, the use of auto-pulling submodules seems like quite a hack in our setup... I wonder if we should/could drop them, in favour of separate ordinary clones somehow.

**Comment by mscherer** [comment]
So I pushed a fix, but I am not keen on putting it in production on friday evening when I am supposed to be out for the weekend, so i will delay that for monday (or I forgot about some auto updater and I will be paged, but I guess I would deserve it for leaving on the edge)

**Comment by mscherer** [comment]
I also rewrote the build script today. I am currently testing it, but it should make this fix cleaner.

**Comment by JPrause** [comment]
@mscherer if this is now resolved,..please close this issue.
