### ISSUE TITLE
Developer setup page has a wrong bundler version mention

### ISSUE THREAD

**Issue by abonas** [ManageIQ/manageiq.org#239]
this page:
http://manageiq.org/documentation/development/developer_setup/

states:
"gem install bundler -v "~>1.7.4""

however the manageiq master has in Gemfile:
 "bundler",       ">= 1.8.4"
and so installing per the instructions with 1.7 fails "bundle install" in the middle.

**Comment by abonas** [comment]
cc @chessbyte @matthewd - encountered it after upgrading to ruby 2.2, left a comment also in talk.manageiq on the ruby 2.2 thread.
http://talk.manageiq.org/t/bumping-minimum-ruby-to-2-2/950/2

**Comment by abonas** [comment]
@chessbyte is there any reason this needs to take this long to resolve?

**Comment by chrisarcand** [comment]
@abonas I'm guessing this took this long because the line you mention (1.7.4) was already removed from the guides and it's unlikely people accidentally install such a low version of bundler at this point. I added bundler help to a PR anyway to avoid confusion on freshly installed rubies.

**Comment by JPrause** [comment]
@abonas seems this is now resolved,...please close this issue.
With Ruby installed, gem install bundler to install the latest Bundler. Required Bundler version is 1.8.7+
