### ISSUE TITLE
Bad REST API doc links

### ISSUE THREAD

**Issue by chrisarcand** [ManageIQ/manageiq.org#259]
At http://manageiq.org/documentation/ :

> Want to integrate with ManageIQ? Check out the REST API reference and the REST API specification.

The two links in this section 404 from the move to manageiq_docs: https://github.com/ManageIQ/guides/blob/4361d20c3a848e416c64aa0ab0fa6cc89db2ad12/rest_api.md

Thanks @riv2q for reporting this issue in the ManageIQ/manageiq Gitter chat.

**Comment by chrisarcand** [comment]
cc/ @abellotti

**Comment by abellotti** [comment]
cc/ @mfeifer 
Not sure who maintains manageiq.org/documentation.

Goal is to have the docs in http://github.com/manageiq_docs pushed up to something like docs.manageiq.org, similar to how we push nightly builds to releases.manageiq.org, the above site can then be updated accordingly.

**Comment by mfeifer** [comment]
@fryguy I know that I've seen some emails going back and forth on this.
Can you comment?

On Mon, Jan 11, 2016 at 9:21 AM, Alberto Bellotti <notifications@github.com>
wrote:

> cc/ @mfeifer <https://github.com/mfeifer>
> Not sure who maintains manageiq.org/documentation.
>
> Goal is to have the docs in http://github.com/manageiq_docs
> <https://github.com/manageiq_docs> pushed up to something like
> docs.manageiq.org, similar to how we push nightly builds to
> releases.manageiq.org, the above site can then be updated accordingly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ManageIQ/manageiq.org/issues/259#issuecomment-170565162>
> .
>



-- 
Marianne Feifer
Senior Technical Project Manager
CloudForms Management Engine
Certified Scrum Master
mfeifer@redhat.com
irc: mfeifer
freenode: marigold

**Comment by JPrause** [comment]
@chrisarcand if this is now resolved, can you close this issue.
