### ISSUE TITLE
Missing from developer_setup page minimal version required for postgresql

### ISSUE THREAD

**Issue by abonas** [ManageIQ/manageiq.org#264]

**Comment by chessbyte** [comment]
@matthewd @Fryguy @mfeifer would you please address

**Comment by abonas** [comment]
@chessbyte is there any reason this needs to take this long to resolve?

**Comment by Fryguy** [comment]
@abonas Pull requests are welcome

**Comment by abonas** [comment]
@Fryguy I would have gladly sent a PR, however I do not possess the relevant knowledge. The decision on the db version is made by the core team, and the purpose of this issue is to make this information available to contributors outside of core team. I'm assuming this is why @chessbyte asked specific people to address it.

**Comment by JPrause** [comment]
@abonas this issue seems to be resolved. See: http://manageiq.org/documentation/development/developer_setup/         Required PostgreSQL version is 9.4+
Can you close this issue.

**Comment by abonas** [comment]
@JPrause afaik it is now 9.5, not 9.4. please check with the core team.

**Comment by Fryguy** [comment]
It is 9.4+ .  9.5 is only required if you want to use the pglogical based replication.
