### ISSUE TITLE
Broken downlaod link for RHEV

### ISSUE THREAD

**Issue by vprusa** [ManageIQ/manageiq.org#271]
At http://manageiq.org/download/ choose RHEV and for both stable and nightly the "Download ManageIQ for Red Hat Enterprise Virtualization" link is broken

Stable: http://82396214b15770b3002a-d3fd4008af5431479c47090ec0cc5a4d.r13.cf5.rackcdn.com//manageiq-rhev-capablanca-2.ova
Nightly: http://releases.manageiq.org/manageiq-rhev-devel.ova

**Comment by itamarh** [comment]
I assume the RHEV one is a mistake, as for RHEV it would be CloudForms from Red Hat Portal. the oVirt (RHEV's upstream) one is the closest match probably.

**Comment by arnikasky** [comment]
@itamarh No. I have architecture: RHEV + ManageiQ, so i want be able to download the ManageiQ for RHEV

**Comment by chessbyte** [comment]
@Fryguy I thought you had fixed this.

**Comment by Fryguy** [comment]
I did, but it wasn't merged yet :( 

https://github.com/ManageIQ/manageiq.org/pull/272

**Comment by Fryguy** [comment]
Closed in #272
