### ISSUE TITLE
Julian Cheal missing from team page

### ISSUE THREAD

**Issue by chrisarcand** [ManageIQ/manageiq.org#277]
@juliancheal needs to add himself to the [the team page](http://manageiq.org/community/team/) ^_^

**Comment by juliancheal** [comment]
I didn't even realise about that page!

**Comment by JPrause** [comment]
@chrisarcand I think you can close this since I just submitted: https://github.com/ManageIQ/manageiq.org/pull/344 which should resolve this request.

**Comment by chrisarcand** [comment]
You can add `Closes #<The PR number>` to the description of 344 and this will automatically be closed when that's merged 😃  https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by JPrause** [comment]
@chrisarcand this request is now resolved and you can close this issue. (not sure why my reference didn't work to close this auto-magically)

**Comment by chrisarcand** [comment]
@JPrause Oop, didn't close automatically because the "Closes/Fixes #XXX" needs to be in the PR description or commit message (yours was a comment). 👍
