### ISSUE TITLE
Middleman fails to come up in development mode

### ISSUE THREAD

**Issue by imtayadeway** [ManageIQ/manageiq.org#332]
I previously ran into this issue and believe @syncrou has encountered the same.  I believe the workaround was to create empty file `source/documentation/development/README.html`. Removing the file, however, is not sufficient for me to recreate the issue now. @syncrou do you still have the backtrace?

**Comment by syncrou** [comment]
@imtayadeway - Yes - Here it is: (included the start line as well.)

`dbomhof@syncrou ~/syncrou/manageiq.org (master)]$ ./run-server.sh
== The Middleman is loading`

`Updating git submodules...
Synchronizing submodule url for 'source/depot/extension'
Synchronizing submodule url for 'source/documentation/development'`


`== Administration is at http://0.0.0.0:4567/admin/
/Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/extensions/proxies.rb:46:in 'proxied_to_resource': Path documentation/development/index.html proxies to unknown file documentation/development/README.html:[] (RuntimeError)
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/extensions/proxies.rb:59:in 'get_source_file'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:33:in 'source_file'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:62:in 'metadata'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-blog-3.5.3/lib/middleman-blog/paginator.rb:26:in 'block in manipulate_resource_list'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-blog-3.5.3/lib/middleman-blog/paginator.rb:22:in 'each'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-blog-3.5.3/lib/middleman-blog/paginator.rb:22:in 'manipulate_resource_list'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/store.rb:215:in 'block (2 levels) in ensure_resource_list_updated!'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/store.rb:214:in 'each'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/store.rb:214:in 'reduce'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/store.rb:214:in 'block in ensure_resource_list_updated!'
	from /Users/dbomhof/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in 'mon_synchronize'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/store.rb:208:in 'ensure_resource_list_updated!'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/extensions/on_disk.rb:31:in 'block in initialize'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/uber-0.0.15/lib/uber/options.rb:96:in 'instance_exec'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/uber-0.0.15/lib/uber/options.rb:96:in 'proc!'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/uber-0.0.15/lib/uber/options.rb:82:in 'evaluate_for'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/uber-0.0.15/lib/uber/options.rb:60:in 'call'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/hooks-0.4.1/lib/hooks/hook.rb:59:in 'evaluate_callback'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/hooks-0.4.1/lib/hooks/hook.rb:55:in 'execute_callback'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/hooks-0.4.1/lib/hooks/hook.rb:40:in 'block in run'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in 'each'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in 'inject'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in 'run'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/hooks-0.4.1/lib/hooks.rb:55:in 'run_hook_for'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/hooks-0.4.1/lib/hooks/instance_hooks.rb:6:in 'run_hook'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:57:in 'inst'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/preview_server.rb:107:in 'new_app'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/preview_server.rb:24:in 'start'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/cli/server.rb:81:in 'server'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:72:in 'method_missing'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/thor-0.19.1/lib/thor/command.rb:29:in 'run'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/thor-0.19.1/lib/thor/command.rb:126:in 'run'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:20:in 'start'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/gems/middleman-core-3.3.12/bin/middleman:18:in '<top (required)>'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/bin/middleman:23:in 'load'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/bin/middleman:23:in '<main>'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/bin/ruby_executable_hooks:15:in 'eval'
	from /Users/dbomhof/.rvm/gems/ruby-2.3.0@manageiq.org/bin/ruby_executable_hooks:15:in '<main>'`

**Comment by Fryguy** [comment]
Closing since the new website is now live.  If you believe this to be in error, please reopen this issue.
