### ISSUE TITLE
Instructions for uploading ManageIQ in RHEV reference rhevm-image-uploader

### ISSUE THREAD

**Issue by jeromemarc** [ManageIQ/manageiq.org#347]
The correct command name is engine-image-uploader instead of rhevm-image-uploader.
See: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.6/html/Administration_Guide/sect-The_Image_Uploader_Tool.html

**Comment by Fryguy** [comment]
@hayesr I didn't close this one as we should keep it in mind when we add the instructions back (if we choose to)

**Comment by hayesr** [comment]
Closing this for now. I'm not sure where the error is, but it probably refers to documentation in the [ManageIQ/manageiq_docs](https://github.com/ManageIQ/manageiq_docs) repo.
