### ISSUE TITLE
New site: blog width is squished on large displays

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq.org#378]
Compare the screenshots in chrome 53 at 2560x1440

![image](https://cloud.githubusercontent.com/assets/19339/19248633/4d4952d2-8eff-11e6-99ff-583c677d7aab.png)

![image](https://cloud.githubusercontent.com/assets/19339/19248643/5728c0da-8eff-11e6-9b70-63e255819e47.png)

![image](https://cloud.githubusercontent.com/assets/19339/19248658/6268d372-8eff-11e6-9088-6248e75f8fc8.png)

![image](https://cloud.githubusercontent.com/assets/19339/19248690/821d533c-8eff-11e6-9586-59aa626b1942.png)

cc @hayesr

**Comment by jrafanie** [comment]
Note, this might be intentional in order for it to display correctly on mobile.  Just thought it looked weird.

**Comment by hayesr** [comment]
The intention was to support the static design from UX first, then adapt for different screens. (This is still in process 😃 ) My plan is to let the content stretch a bit and increase the font-size for very wide screens.

**Comment by hayesr** [comment]
Also, if someone would be willing to donate, say a 4K monitor to the cause it would really help things get going 😜

**Comment by jrafanie** [comment]
> The intention was to support the static design from UX first, then adapt for different screens. (This is still in process 😃 ) My plan is to let the content stretch a bit and increase the font-size for very wide screens.

@hayesr Great, no problem.  It was not a big deal but obvious enough that it was worth taking some screenshots and opening an issue.
