### ISSUE TITLE
On the old site there was a link for instructions to submit a pull request. I can't find that page anywhere on the site now.

### ISSUE THREAD

**Issue by ramrexx** [ManageIQ/manageiq.org#393]

**Comment by romanblanco** [comment]
@ramrexx Is [this](http://manageiq.org/docs/guides/coding_style_and_standards#pull-requests-and-branches) what are you looking for? 😊

**Comment by JPrause** [comment]
@ramrexx it seems that @romanblanco has pointed to the doc you're looking for,...do you agree. If so, please close this issue.

**Comment by ramrexx** [comment]
Great. Looks like the link provided is working again.
