### ISSUE TITLE
Links to documentation do no longer work

### ISSUE THREAD

**Issue by evertmulder** [ManageIQ/manageiq.org#394]
Links to documentation do no longer work: For example:
http://manageiq.org/pdf/ManageIQ-0-General_Configuration-en-US.pdf

**Comment by hayesr** [comment]
Until we can replace them in the new website, I've made the PDFs available here https://goo.gl/ysi0yY

**Comment by evertmulder** [comment]
Thanks a lot for your quick response. That solves the issue for me!
