### ISSUE TITLE
Vagrant missing for stable/pre-release in download page

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq.org#419]
For 'stable' (darga): https://atlas.hashicorp.com/manageiq/boxes/darga

For 'pre-release' (euwe): https://atlas.hashicorp.com/manageiq/boxes/euwe

Also, for 'nightly', we don't currently upload to atlas and it can be downloaded only from releases.manageiq.org.  So linking to atlas might not be a good idea.

**Comment by cybette** [comment]
Fixed in #421 

@simaishi does [this](http://manageiq.org/download/) solve all the issues?
