### ISSUE TITLE
Site shows in mobile mode even on 1400x1300 desktop screen

### ISSUE THREAD

**Issue by pilhuhn** [ManageIQ/manageiq.org#432]
This is on Safari  10.0.1 / OSX Sierra 12.1
The shown browser window is 1400x1300 px in size

![bildschirmfoto 2016-11-14 um 15 35 58](https://cloud.githubusercontent.com/assets/208246/20268717/9cbad592-aa80-11e6-9962-6d6bbe309a25.png)
![bildschirmfoto 2016-11-14 um 15 36 03](https://cloud.githubusercontent.com/assets/208246/20268715/9ca81fc4-aa80-11e6-8d41-1c708f9f7066.png)
![bildschirmfoto 2016-11-14 um 15 36 26](https://cloud.githubusercontent.com/assets/208246/20268716/9cad145c-aa80-11e6-9d76-1d67af8ff5fc.png)

**Comment by Terones** [comment]
Hi @pilhuhn,
I recently got myself a Mac and tried to reproduce this behavior. 
I only get the mobile view if I reduce the window size, but that appears not the case when looking at your screenshots. Or when I increase the "Page Zoom" to 150% or larger which is under Safari > preferences... > Advanced. 

![screen_shot_manageiq_org](https://user-images.githubusercontent.com/5983433/27226109-b587c1dc-529d-11e7-9c01-5efdab0cbd3d.png)

**Comment by epwinchell** [comment]
The site drops to mobile mode at 985px. A larger than normal font size in browser ("zoom in" in Safari) was probably the culprit.
