### ISSUE TITLE
Getting 404 for links on talk that point to manageiq.org

### ISSUE THREAD

**Issue by JPrause** [ManageIQ/manageiq.org#442]
If you look here: http://talk.manageiq.org/about
At the top, the following button redirect to missing pages on manageiq.org
FAQ: http://manageiq.org/documentation/faq/
Terms of Service: http://manageiq.org/terms-of-use

**Comment by hayesr** [comment]
I don't think we have an FAQ anymore. Correct TOS would be [this url](https://manageiq.org/legal/) I suppose.

**Comment by JPrause** [comment]
@cybette I looked around in the admin settings but didn't want to muck around. Can you edit these links.

**Comment by cybette** [comment]
Ok I'll do that, thanks!

**Comment by cybette** [comment]
Pointed TOS to http://manageiq.org/legal/terms-of-use/

[Couldn't rename or remove FAQ at the moment](https://meta.discourse.org/t/change-faq-tos-etc-menu-captions/31961), so linking it to "FAQ/Guidelines" even though it's really just Guidelines

@JPrause does this cover all the issues?

**Comment by cybette** [comment]
Issues resolved, closing...
