### ISSUE TITLE
Convert DocBook to Markdown

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#47]
I've been trying to convert DocBook to AsciiDoc, but it really seems that the support to do so — at least for our DocBook files — is quite lacking. (I have run into the same issues that Dan Macpherson has.) 

Converting to Markdown seems more robust and better supported... so now I am looking into variants of Markdown that would best allow for GitHub-flavored extensions and other additional markup as one possible solution. (See issue #46)

--

Another option is to use MediaWiki's mockup... but I'm trying to use Markdown instead, as that's what the team is already familiar with and what is much more native on GitHub. (It renders Markdown beautifully already. I don't think that's the case for MediaWiki formatted files.)

--

During our call today, it was decided that we should probably go with an all-in-one page instead of separate pages per chapter. The headings would have IDs so each would be hot-link-able, enabling other pages to link directly to a section.

So, no matter the format we choose, whether AsciiDoc or Markdown, it should be in one page and have header IDs.

**Comment by JPrause** [comment]
With the upcoming redesign of the website, this request seems not be relevant at this time,..can you close this issue @garrett

**Comment by Fryguy** [comment]
Closing since the new website is now live.  If you believe this to be in error, please reopen this issue.
