### ISSUE TITLE
Improve tests to catch build problems

### ISSUE THREAD

**Issue by hayesr** [ManageIQ/manageiq.org#474]
Currently Travis is only building the site, not running tests. Also, it might be possible to write something to catch if the latest blog post is generated.

**Comment by JPrause** [comment]
@cybette I think Smitty has resolved this issue. Your thoughts? Can this be closed?

**Comment by cybette** [comment]
What Smitty did was the listener to trigger a build, and fix the IPs on the Docker side. There's still no tests to catch build problems and automatically detect if blog post is generated (if there was, we wouldn't have to manually check every time). However, unless we have specific tests in mind we'd like Smitty to work on, I think we can close this.
