### ISSUE TITLE
Create a `humans.txt`

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#49]
As mentioned on commit 4a29410 (related to issue #21), we should have a `humans.txt` file, which can be generated from the team YAML file (`data/team.yml`).

Here's the standard: http://humanstxt.org/Standard.html

Here's an example: http://humanstxt.org/humans.txt

**Comment by JPrause** [comment]
With the upcoming redesign of the website, this request seems not be relevant at this time,..can you close this issue @garrett

**Comment by Fryguy** [comment]
Closing since the new website is now live.  If you believe this to be in error, please reopen this issue.
