### ISSUE TITLE
Missing 'Edit this page on GitHub' feature

### ISSUE THREAD

**Issue by romanblanco** [ManageIQ/manageiq.org#491]
It would be great to have the "**Edit this page on GitHub**" button on the bottom of the page. Used to be on the older ManageIQ website, and it's a handy feature, that saves a time.

Is it possible to get it back, @hayesr?

**Comment by romanblanco** [comment]
bump @hayesr

**Comment by romanblanco** [comment]
@miq-bot assign @hayesr

**Comment by hayesr** [comment]
@romanblanco This is something we've wanted since the new launch, just not sure the best way to accomplish it yet with different document sources. I'll get around to it eventually, though 🙂

**Comment by skateman** [comment]
@miq-bot assign @skateman
