### ISSUE TITLE
Add checksum for the images

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq.org#526]
@hayesr We discussed this a while ago, but not sure where we left off... A few things we discussed were:

* create a file that contains SHA for all images for each nightly/release build or 1 file per image?
* keep SHA for every build, or just latest nightly + release builds?

**Comment by simaishi** [comment]
@Fryguy @bdunne I think one of you mentioned json can be parsed? Providing something like this will work?

```
manageiq-azure-devel.json
{
  "date": "2019-12-12"
  "sha256": "9474de767b4c832a048c98044debf7bdcfdd87d73d91c442ca77fa3e572dba8e"
  "size": "1.1 GB"
}
```

This will take care of https://github.com/ManageIQ/manageiq.org/issues/655 and https://github.com/ManageIQ/manageiq.org/issues/694 as well.

**Comment by Fryguy** [comment]
@simaishi Yeah I think that could work

**Comment by chessbyte** [comment]
@simaishi Not clear on the proposal [here](https://github.com/ManageIQ/manageiq.org/issues/526#issuecomment-565497088).  What process will generate the `manageiq-azure-devel.json` file and where will it be stored?

**Comment by simaishi** [comment]
@chessbyte We were thinking we'll create the file during build and upload to the same server where the images are (not sure about the exact location).

**Comment by chessbyte** [comment]
@simaishi that would be cool - then the code that builds the downloads page can validate each downloadable URL it presents against that source of truth.  Let me know when there is something up there and I can make a PR here to validate against it.

**Comment by bdunne** [comment]
There's already the ETag header on the file that can be used to validate the MD5 sum of the file.  Is that good enough?

**Comment by Fryguy** [comment]
ETag is a part of the HEAD request, and I think you can also get the upload date

**Comment by Fryguy** [comment]
> HEAD releases.manageiq.org/manageiq-vsphere-jansa-1-alpha1.ova

```
Content-Length: 1213552640
Last-Modified:  Thu, 26 Mar 2020 12:21:01 GMT
ETag:           556f00b222fc8b04484fc5c9a07163bf
X-Timestamp:    1585225260.49365
```

**Comment by simaishi** [comment]
Ah, `ETag` is enough to cover this issue.

For the nightly build date (https://github.com/ManageIQ/manageiq.org/issues/655), we probably want to get it from the file name as build date isn't upload date?

And if we want to validate what we built is what was uploaded, then we'll need to generate something at build time, but that's a different issue, I guess.

**Comment by Fryguy** [comment]
I'm less concerned about the validation, though I could see an MD5 generated on the build side and uploaded.  MD5 isn't a secure hash, however it's good enough to ensure that someone didn't get a corrupted download.

**Comment by simaishi** [comment]
Agreed, the original request is for users to be able to validate images they downloaded.

**Comment by Fryguy** [comment]
@bdunne If we change hosting does the new hosting have ETag, and, if os, what hash function does it use?

**Comment by bdunne** [comment]
The alternative hosting provider that I'm looking at is the same (ETag using MD5sum)
