### ISSUE TITLE
Get Started guide is out of date

### ISSUE THREAD

**Issue by jgeorgeson** [ManageIQ/manageiq.org#543]
I'm trying to go through the guide with the `fine-1` docker image and it's not going very optimally. In several places the guide either lacks a screenshot or the screenshot doesn't match the product, so I have to start digging around to try and find something resembling the guide. For example the very first post-login screenshot, showing the main and secondary menus has a **Settings** item which doesn't exist in `fine-1`. right after the screenshot we're told to use the **Settings** menu that doesn't exist. In the chapter on creating a service dialog it simply says _Add a tab_ with no indication how to do that. There's no link/button in the section of the _Add a Dialog_ dialog where it lists tabs, and I was told on Gitter room to use the non-discript and unlabled '+' combobox up in the top-left corner.

I like the product itself so far, but quick start introductory guide needs to be bulletproof. When it's out of date and doesn't match the product (and I'm running the Docker image version specified in the _Get Started_ guide) that leaves an overall negative impression for new users.

**Comment by JPrause** [comment]
@jgeorgeson I'm working on the updates: https://github.com/ManageIQ/manageiq.org/pull/588

**Comment by JPrause** [comment]
This should now be resolved. @jgeorgeson can you have a look and if good, can you close this issue.
