### ISSUE TITLE
The RHEV install guide is missing

### ISSUE THREAD

**Issue by JPrause** [ManageIQ/manageiq.org#544]
http://manageiq.org/docs/reference/latest/doc-Installing_on_Red_Hat_Enterprise_Virtualization/miq
Produces: 404 Not Found

**Comment by cybette** [comment]
Another 404: http://manageiq.org/docs/get-started/add-a-provider -> link 'support option documents'

**Comment by JPrause** [comment]
I'll open that one as well

**Comment by JPrause** [comment]
nevermind,..I see it on the same issue.

**Comment by cybette** [comment]
grouping 404's together for now, will also do a more thorough check in the docs as I'm going through them.

**Comment by JPrause** [comment]
another 404: On page http://manageiq.org/docs/reference/latest/doc-Installing_on_Google_Compute_Engine/miq/
-> 1. In a browser, navigate to manageiq.org/download
goes to http://manageiq.org/docs/reference/latest/doc-Installing_on_Google_Compute_Engine/miq/manageiq.org/download

**Comment by hayesr** [comment]
@JPrause That last one is probably an issue for [Docs](https://github.com/ManageIQ/manageiq_docs).

**Comment by hayesr** [comment]
@JPrause Where did you run into the link to _Enterprise_ Virtualization? The docs appear to have both, the website menu is currently linking to the non-enterprise version.

**Comment by JPrause** [comment]
@hayesr if you go to http://manageiq.org/docs/reference/ 
On the left panel, click on Installation and the drop down has the Red Hat Enterprise Virtualization 404 link.
Also, on the page itself, under the Installation heading,..the link is there as well.

**Comment by JPrause** [comment]
It appears that these link are now fixed. Closing issue.
