### ISSUE TITLE
Update events on community page

### ISSUE THREAD

**Issue by cybette** [ManageIQ/manageiq.org#550]
ManageIQ at upcoming events:
- AnsibleFest London https://www.ansible.com/ansiblefest/london
- Ruby User Group Vienna meetup https://www.meetup.com/vienna-rb/events/239689512/

Move OpenExpo from Upcoming to Past

Another past event:
- OSDC http://osdc.de with couple talks on ManageIQ: https://www.netways.de/en/events/osdc/archive/osdc2017/talks/

@Terones would you help update these? thanks!

**Comment by Terones** [comment]
Thanks, I'll look into it this evening.

**Comment by cybette** [comment]
Thanks @Terones for PR to address the issue.
