### ISSUE TITLE
ask.manageiq.org - email confirmation goes to spam on gmail

### ISSUE THREAD

**Issue by dneary** [ManageIQ/manageiq.org#56]
From issue #35 : 

@FryGuy said:
> Ok, so I tried logging in with my gmail (Google+) account, and I seem to have gotten to where it send me a confirmation email. So I waited and waited...and realized maybe its in spam. Sure enough there it was. I think the problem is that the "from" email address is "evgeny.fadeev@gmail.com", and the details on why it was marked as spam are here. I'm happy to see that @dneary notified a Evgeny in his last comment, otherwise, I'd be super confused.
> 
> Would it be possible to have the email come from talk-do-not-reply@manageiq.org or something?

**Comment by mscherer** [comment]
Since ask.manageiq.org is no longer in production, closing.
