### ISSUE TITLE
DOC: We need to add minimum requirements when using Google Compute Engine images

### ISSUE THREAD

**Issue by JPrause** [ManageIQ/manageiq.org#573]
It appears that we have minimum reqs defined for:
http://manageiq.org/docs/reference/latest/doc-Installing_on_Microsoft_Azure/miq/
http://manageiq.org/docs/reference/latest/doc-Installing_on_Red_Hat_Enterprise_Linux_OpenStack_Platform/miq/
http://manageiq.org/docs/reference/latest/doc-Installing_on_Red_Hat_Virtualization/miq/

but we have no such min reqs defined for Google Compute Engine:
http://manageiq.org/docs/reference/latest/doc-Installing_on_Google_Compute_Engine/miq/

It appears we document the min req to be:
4 cores
12Gb RAM
44GB disk space

**Comment by FlorianOnmyown** [comment]
Hi @JPrause,

This will be updated as soon as the following PR will be merged: https://github.com/ManageIQ/manageiq_docs/pull/525

**Comment by JPrause** [comment]
Excellent @FlorianOnmyown !!! You're on a roll. :-)
I'll review PR525

**Comment by JPrause** [comment]
This appears to be strictly a docs repo issue, I think we can close this one, since PR525 resolves this issue.
