### ISSUE TITLE
DOC: Conflicting instruction for Openstack minimum requirements

### ISSUE THREAD

**Issue by JPrause** [ManageIQ/manageiq.org#574]
http://manageiq.org/docs/reference/latest/doc-Installing_on_Red_Hat_Enterprise_Linux_OpenStack_Platform/miq/

1.4. Creating a Custom Flavor
We state that 12 GB RAM in the minimum req, but then on step 4. the doc says to enter RAM MB: 8192

We should be consistent. All other deployments also req 12GB RAM.

**Comment by FlorianOnmyown** [comment]
@JPrause this will be solved once the following pull request will be merged: https://github.com/ManageIQ/manageiq_docs/pull/526

**Comment by JPrause** [comment]
Resolved. Thanks @FlorianOnmyown
