### ISSUE TITLE
ovirt qc2 files are being built, need to add them to the download page

### ISSUE THREAD

**Issue by JPrause** [ManageIQ/manageiq.org#613]
Smitty pointed out that:

In section 1.2 of http://www.manageiq.org/docs/reference/latest/doc-Installing_on_Red_Hat_Virtualization/miq/, it says to use QCOW2 for RHV 4.0 and newer.

However, when you go to the download page, there is no qcow2 option, just ovirt.

**Comment by JPrause** [comment]
@miq-bot assign cybette

**Comment by cybette** [comment]
Issue resolved with https://github.com/ManageIQ/manageiq.org/pull/616

@JPrause please check and close this if everything looks ok!

**Comment by JPrause** [comment]
Checked download page. Yeh! LGTM, closing issue.
