### ISSUE TITLE
Need to add Gaprindashvili link to http://manageiq.org/docs/reference/

### ISSUE THREAD

**Issue by JPrause** [ManageIQ/manageiq.org#625]
@hayesr jumped in and offered the following as reference:

When _config.yml is updated we need a menu under site/data/menus 
There is a menu generator that will attempt to auto-generate this. At the time the state of the docs repo was too messy to make this fully-automatic, so manual editing of these menu files was necessary.
A PR might be easy, but it needs eyes familiar with what docs should be displayed to finish it.
Ugh, there’s also an ENV to change …

**Comment by JPrause** [comment]
@miq-bot assign @epwinchell

**Comment by hayesr** [comment]
Unfortunately, how this works is a bit complicated 😬  There are 2 big pieces:

## Selecting which branches to process
This is controlled with an ENV var (comma-separated string) and used during the build time. See [this line in miq.rb](https://github.com/ManageIQ/manageiq.org/blob/master/lib/miq.rb#L84). To add Gaprindashvili, either set the ENV var on the server, in the Dockerfile, or change the default in `miq.rb`.

This will tell the build process to include the `gaprindashvili` branch (assuming there is one) when processing the docs repo. There should then be converted html files under `dest/docs/reference/gaprindashvili`. This also controls which branches are displayed at the top of a doc page.

## Displaying the docs
Next we need to link to the converted docs. Back when I built this, the organization of the docs didn't match the way we wanted it on the site so the menus couldn't be fully automated, but we can get a start at least …

### Generating the side menu
(do this locally from the project dir) `bin/miq build reference` will pull the docs from Github, then process them. `bin/miq build menus` will generate YAML files under `tmp` based on the structure of the processed files. They need to be changed to the desired structure for the website (see other menu files under site/_data/menus). Make sure to prefix the menu file with `ref_menu_`, _eg_ `ref_menu_gaprindashvili` and put it under `site/_data/menus`. I'm pretty sure all that's necessary to get the menu working.

### Index page
Each release also has a manually created "index" page under `site/docs/reference`. Duplicating one of them and changing the `doc_branch` var at the top should be sufficient, but feel free to make this completely different if a release warrants that.

---------------
Hopefully that covers it!

**Comment by skateman** [comment]
@hayesr I'm trying to follow your steps and it seems working, except the newly generated docs are missing the template around. I know that folder should be added to the gitignore, but I wanted to show you somehow. Do you have any ideas why this is happening?

https://github.com/skateman/manageiq.org/tree/gaprindashvili-docs/site/docs/reference/gaprindashvili

**Comment by hayesr** [comment]
Yes, that's expected. The docs are converted from Asciidoc in a minimal way and put under `site/docs` so that when the Jekyll build happens they get the same template "wrapper" that all the other content does.

**Comment by skateman** [comment]
@hayesr thanks, but how to add the template around them?

**Comment by hayesr** [comment]
@skateman I don't think you need to do anything except build the site. `bin/miq build site` IIRC. In other words, there are a couple of stages to the whole thing: getting the docs into a format that Jekyll wants, then letting Jekyll do its thing as if the docs were manually created pages.

**Comment by hayesr** [comment]
@skateman Also there's `site/_config.yml`. At the bottom under `defaults:` is where we tell Jekyll to apply a certain layout to specific doc directories.

**Comment by skateman** [comment]
@hayesr thanks, it works now!
