### ISSUE TITLE
Create documentation for how to translate/localize ManageIQ

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#63]
Quoth @dneary:

> We will need to check whether there is a way to handle translations already with the developers, if there isn't then it may need to be a higher priority (as that is often the quickest way for newcomers to productively contribute to a community project).

...So:

1. Is ManageIQ translatable?
2. Are there existing docs on how to translate it?

**Comment by JPrause** [comment]
With the upcoming redesign of the website, this request seems not be relevant at this time,..can you close this issue @garrett

**Comment by Fryguy** [comment]
Closing since the new website is now live.  If you believe this to be in error, please reopen this issue.
