### ISSUE TITLE
404s in API Docs Reference

### ISSUE THREAD

**Issue by shaunix** [ManageIQ/manageiq.org#659]
I'm seeing lots of 404s when clicking things under Reference in the sidebar here:
http://manageiq.org/docs/reference/latest/api/reference/collections

**Comment by JPrause** [comment]
Thanks @shaunix and I see what you're reporting as well.
We'll get this resolved asap.

**Comment by cybette** [comment]
Should be fixed by https://github.com/ManageIQ/manageiq.org/pull/660 and https://github.com/ManageIQ/manageiq.org/pull/662

Please confirm and close issue.

**Comment by epwinchell** [comment]
Confirmed this is no longer an issue.
