### ISSUE TITLE
manageiq.org/community issue

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq.org#690]
Pls see following screenshot for web page issue.
![image](https://user-images.githubusercontent.com/378638/49545128-589ee980-f8a2-11e8-9e9a-a07bd7286f8c.png)

**Comment by Fryguy** [comment]
@cybette Not sure who needs to work on this.

**Comment by JPrause** [comment]
It also looks like the Facebook icon on that page is missing? Other SoMe icons appear to be okay.

The direct link in the iframe https://www.openhub.net/p/manageiq/widgets/project_basic_stats does show the correct data.

@epwinchell is this something you could pin down as to why this is happening?

**Comment by cybette** [comment]
This page needs updating, I'll take a look after the holidays and make sure all the bugs are fixed. Thanks for pointing them out!

**Comment by epwinchell** [comment]
@JPrause @cybette  - @skateman says it's a it's a jekyll issue

**Comment by skateman** [comment]
looking ...

**Comment by skateman** [comment]
Not a jekyll issue, misread the line ... working on it anyway.
