### ISSUE TITLE
Info for downloads should be refactored into the appropriate files to make updating easier

### ISSUE THREAD

**Issue by cybette** [ManageIQ/manageiq.org#695]
Download index page should be refactored so everything about releases (branch name, box name, etc.) live in `site/_data/releases.yaml` and everything about image details live in `site/_data/download_types.yaml`

From https://github.com/ManageIQ/manageiq.org/pull/693

**Comment by chessbyte** [comment]
@cybette seems like this is done.  Can you either elaborate or close the issue?

**Comment by cybette** [comment]
Thanks @chessbyte, looks like this has been covered. Closing issue.
