### ISSUE TITLE
Edit page on github button on doc pages

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq.org#741]
Would be nice to expose an "Edit this page on GitHub" button where we are we have content that is changing. Just a simple link that takes you to the github repo and opens the editor.

**Comment by skateman** [comment]
cc @romanblanco 
@miq-bot assign @skateman 
@epwinchell would you be okay with this?

**Comment by epwinchell** [comment]
closing in favor of: https://github.com/ManageIQ/manageiq.org/issues/491
