### ISSUE TITLE
Update "edit this page on github" to work with imported git submodules

### ISSUE THREAD

**Issue by garrett** [ManageIQ/manageiq.org#75]
It would be nice if the link in the footer was made aware of the git submodule and could point to the correct place on github.

I'm adding this to last-minute milestone, but everything in the prepare-for-launch milestone has kind of shoved everything in the last-minute, as it's now the "last minute" timeframe... so this might have to just be a bug until after launch.

**Comment by JPrause** [comment]
With the upcoming redesign of the website, this request seems not be relevant at this time,..can you close this issue @garrett

**Comment by Fryguy** [comment]
Closing since the new website is now live.  If you believe this to be in error, please reopen this issue.
