### ISSUE TITLE
Improve Auth SAML doc.

### ISSUE THREAD

**Issue by jvlcek** [ManageIQ/manageiq.org#763]
Add the following to the Auth blog posts:

- Describe the time sync issue
- Describe how to enable httpd debug on MiQ
- Describe how hostname must be DNS resolvable.
- Add screenshots for SAML Idp mappers

**Comment by jvlcek** [comment]
@miq-bot assign @jvlcek

**Comment by JPrause** [comment]
@miq-bot assign @jvlcek

**Comment by jvlcek** [comment]
@cybette Please assign this issue to me.
