### ISSUE TITLE
release.manageiq.org has an expired SSL cert.

### ISSUE THREAD

**Issue by dbrandonjohnson** [ManageIQ/manageiq.org#766]
When trying to download I'm seeing the SSL certificate is expired.  It expired back in 2015.

**Comment by bdunne** [comment]
releases.manageiq.org is backed by Rackspace CloudFiles.  At this time, CloudFiles does not allow us to provide a custom certificate for https connections.  https will work, however the certificate you see is issued to `Akamai Technologies, Inc.`.  For this reason, all of the links from the website should point to http, not https
