### ISSUE TITLE
Document security response workflow for ManageIQ

### ISSUE THREAD

**Issue by dneary** [ManageIQ/manageiq.org#79]
The workflow is simple (!) - if you find a security issue, contact security@manageiq.org, which will forward it on to the Red Hat security team, who will apply their typical protocol for security issues related to our products & projects.

It does, however, need to be documented and easy to find on the site. And also on Github. And in CONTRIBUTING.md

**Comment by JPrause** [comment]
With this issue being over 2 years old, and the upcoming redesign of the web-site,..can you close this issue @dneary.
