### ISSUE TITLE
Nightly vagrant download points to a broken link

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq.org#868]
The download page is currently pointing to https://app.vagrantup.com/manageiq/boxes/master for nightly vagrant image. This used to be pointing to http://releases.manageiq.org/manageiq-vagrant-devel.box since we only have boxes for branches and not for 'master'.

Either we should point back to the -devel image or maybe create the 'master' box that points to -devel image?

**Comment by Fryguy** [comment]
I like the idea of having a master box that points to devel.  @simaishi Can you add that?

**Comment by simaishi** [comment]
Added master box for -devel image. Since a version is required, I used "11.0.0-nightly" for now. When we cut K branch and create a new box for it, we can bump the master box to "12.0.0-nightly".

The box can be setup using `vagrant init manageiq/master`.
